"""alter user Migration

Revision ID: 11acd9bfad8f
Revises: 480275aea7e0
Create Date: 2022-05-17 09:50:30.374875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11acd9bfad8f'
down_revision = '480275aea7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
